using System;

using mooSQL.data.model;
using mooSQL.linq.Common;

namespace mooSQL.linq.SqlQuery
{
	/// <summary>
	/// Contains names and create helpers for 假名-functions, generated by linq2db and then converted to database-specific SQL by provider-specific SQL optimizer.
	/// </summary>
	public static class PseudoFunctions
	{
		/// <summary>
		/// Function to convert text parameter to lowercased form: <c>TO_LOWER(string)</c>
		/// </summary>
		public const string TO_LOWER = "$ToLower$";
		public static FunctionWord MakeToLower(IExpWord value)
		{
			return new FunctionWord(typeof(string), TO_LOWER, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAnyParameterNullable, null, value);
		}

		/// <summary>
		/// Function to convert text parameter to uppercased form: <c>TO_UPPER(string)</c>
		/// </summary>
		public const string TO_UPPER = "$ToUpper$";
		public static FunctionWord MakeToUpper(IExpWord value)
		{
			return new FunctionWord(typeof(string), TO_UPPER, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAnyParameterNullable, null, value);
		}

		/// <summary>
		/// Creates cast expression: <c>CAST(value AS to_type)</c>
		/// </summary>
		public static CastWord MakeCast(IExpWord value, DbDataType toType, DataTypeWord? fromType = null)
		{
			return new CastWord(value, toType, fromType);
		}

		/// <summary>
		/// Function to convert value from one type to another: <c>CONVERT(to_type, from_type, value) { CanBeNull = value.CanBeNull }</c>
		/// </summary>
		public const string CONVERT_FORMAT = "$Convert_Format$";

		/// <summary>
		/// Function to convert value from one type to another: <c>CONVERT(to_type, from_type, value) { CanBeNull = value.CanBeNull, DoNotOptimize = true }</c>
		/// </summary>
		public static CastWord MakeMandatoryCast(IExpWord value, DbDataType toType, DataTypeWord? fromType = null)
		{
			return new CastWord(value, toType, fromType, true);
		}

		/// <summary>
		/// Function to convert value from one type to another: <c>TRY_CONVERT(to_type, from_type, value) { CanBeNull = true }</c>.
		/// Returns NULL on conversion failure.
		/// </summary>
		public const string TRY_CONVERT = "$TryConvert$";
		public static FunctionWord MakeTryConvert(DataTypeWord toType, DataTypeWord fromType, IExpWord value)
		{
			return new FunctionWord(toType.SystemType, TRY_CONVERT, false, true, toType, fromType, value)
			{
				CanBeNull = true
			};
		}

		/// <summary>
		/// Function to convert value from one type to another: <c>TRY_CONVERT_OR_DEFAULT(to_type, from_type, value, defaultValue) { CanBeNull = value.CanBeNull || defaultValue.CanBeNull }</c>.
		/// Returns provided default value on conversion failure.
		/// </summary>
		public const string TRY_CONVERT_OR_DEFAULT = "$TryConvertOrDefault$";
		public static FunctionWord MakeTryConvertOrDefault(DataTypeWord toType, DataTypeWord fromType, IExpWord value, IExpWord defaultValue)
		{
			return new FunctionWord(toType.SystemType, TRY_CONVERT_OR_DEFAULT, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAnyParameterNullable, null, toType, fromType, value, defaultValue);
		}

		/// <summary>
		/// Function to replace one text fragment with another in string: <c>REPLACE(value, oldSubstring, newSubstring)</c>
		/// </summary>
		public const string REPLACE = "$Replace$";
		public static FunctionWord MakeReplace(IExpWord value, IExpWord oldSubstring, IExpWord newSubstring)
		{
			return new FunctionWord(typeof(string), REPLACE, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAnyParameterNullable, null, value, oldSubstring, newSubstring);
		}

		/// <summary>
		/// Function to suppress conversion SQL generation for provided value: <c>REMOVE_CONVERT(value, resultType)</c>
		/// </summary>
		public const string REMOVE_CONVERT = "$Convert_Remover$";
		public static FunctionWord MakeRemoveConvert(IExpWord value, DataTypeWord resultType)
		{
			return new FunctionWord(resultType.SystemType, REMOVE_CONVERT, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAnyParameterNullable, null, value, resultType);
		}

		/// <summary>
		/// Function to return first non-null argument: <c>COALESCE(values...)</c>
		/// </summary>
		public const string COALESCE = "$Coalesce$";
		public static FunctionWord MakeCoalesce(Type systemType, params IExpWord[] values)
		{
			return new FunctionWord(systemType, COALESCE, false, true, PrecedenceLv.Primary,
				ParametersNullabilityType.IfAllParametersNullable, null, values);
		}
	}
}
