// <auto-generated />
#nullable enable

using mooSQL.linq.Expressions;

using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;

namespace mooSQL.linq.Linq.Builder;

partial class ExpressionBuilder
{
	private static class Builder<T> where T : ISequenceBuilder, new()
	{
		public static readonly T Instance = new();
	}

	private static partial ISequenceBuilder? FindBuilderImpl(BuildInfo info, ExpressionBuilder builder)
	{
		var expr = info.Expression = info.Expression.Unwrap();
		switch (expr.NodeType)
		{
			case ExpressionType.Constant:
				if (global::mooSQL.linq.Linq.Builder.EnumerableBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.EnumerableBuilder>.Instance;

				break;

			case ExpressionType.MemberAccess:
				if (global::mooSQL.linq.Linq.Builder.EnumerableBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.EnumerableBuilder>.Instance;

				break;

			case ExpressionType.NewArrayInit:
				if (global::mooSQL.linq.Linq.Builder.EnumerableBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.EnumerableBuilder>.Instance;

				break;

			case ExpressionType.Lambda:
				if (global::mooSQL.linq.Linq.Builder.ScalarSelectBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.ScalarSelectBuilder>.Instance;

				break;


			case ExpressionType.Call:
			{
				var call = (MethodCallExpression)expr;
				switch (call.Method.Name)
				{
					case "Alias":
						if (global::mooSQL.linq.Linq.Builder.PassThroughBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.PassThroughBuilder>.Instance;

						break;

					case "All":
						if (global::mooSQL.linq.Linq.Builder.AllAnyBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllAnyBuilder>.Instance;

						break;

					case "AllAsync":
						if (global::mooSQL.linq.Linq.Builder.AllAnyBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllAnyBuilder>.Instance;

						break;

					case "Any":
						if (global::mooSQL.linq.Linq.Builder.AllAnyBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllAnyBuilder>.Instance;

						break;

					case "AnyAsync":
						if (global::mooSQL.linq.Linq.Builder.AllAnyBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllAnyBuilder>.Instance;

						break;

					case "AsCte":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildKnownMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "AsQueryable":
						if (global::mooSQL.linq.Linq.Builder.PassThroughBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.PassThroughBuilder>.Instance;

						break;

					case "AsSubQuery":
						if (global::mooSQL.linq.Linq.Builder.AsSubQueryBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AsSubQueryBuilder>.Instance;

						break;

					case "AsUpdatable":
						if (global::mooSQL.linq.Linq.Builder.AsUpdatableBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AsUpdatableBuilder>.Instance;

						break;

					case "AsValueInsertable":
						if (global::mooSQL.linq.Linq.Builder.AsValueInsertableBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AsValueInsertableBuilder>.Instance;

						break;

					case "Average":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "AverageAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "Cast":
						if (global::mooSQL.linq.Linq.Builder.CastBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.CastBuilder>.Instance;

						break;

					case "Concat":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "Contains":
						if (global::mooSQL.linq.Linq.Builder.ContainsBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ContainsBuilder>.Instance;

						break;

					case "ContainsAsync":
						if (global::mooSQL.linq.Linq.Builder.ContainsBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ContainsBuilder>.Instance;

						break;

					case "Count":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "CountAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "CrossJoin":
						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						break;

					case "DatabaseName":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "DefaultIfEmpty":
						if (global::mooSQL.linq.Linq.Builder.DefaultIfEmptyBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DefaultIfEmptyBuilder>.Instance;

						break;

					case "Delete":
						if (global::mooSQL.linq.Linq.Builder.DeleteBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DeleteBuilder>.Instance;

						break;

					case "DeleteWhenMatchedAnd":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.DeleteWhenMatched.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.DeleteWhenMatched>.Instance;

						break;

					case "DeleteWhenNotMatchedBySourceAnd":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.DeleteWhenNotMatchedBySource.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.DeleteWhenNotMatchedBySource>.Instance;

						break;

					case "DeleteWithOutput":
						if (global::mooSQL.linq.Linq.Builder.DeleteBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DeleteBuilder>.Instance;

						break;

					case "DeleteWithOutputInto":
						if (global::mooSQL.linq.Linq.Builder.DeleteBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DeleteBuilder>.Instance;

						break;

					case "DisableGuard":
						if (global::mooSQL.linq.Linq.Builder.DisableGroupingGuardBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DisableGroupingGuardBuilder>.Instance;

						break;

					case "Distinct":
						if (global::mooSQL.linq.Linq.Builder.DistinctBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DistinctBuilder>.Instance;

						break;

					case "Drop":
						if (global::mooSQL.linq.Linq.Builder.DropBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DropBuilder>.Instance;

						break;

					case "ElementAt":
						if (global::mooSQL.linq.Linq.Builder.ElementAtBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ElementAtBuilder>.Instance;

						break;

					case "ElementAtAsync":
						if (global::mooSQL.linq.Linq.Builder.ElementAtBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ElementAtBuilder>.Instance;

						break;

					case "ElementAtOrDefault":
						if (global::mooSQL.linq.Linq.Builder.ElementAtBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ElementAtBuilder>.Instance;

						break;

					case "ElementAtOrDefaultAsync":
						if (global::mooSQL.linq.Linq.Builder.ElementAtBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.ElementAtBuilder>.Instance;

						break;

					case "Else":
						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "Except":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "ExceptAll":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "First":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "FirstAsync":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "FirstOrDefault":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "FirstOrDefaultAsync":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "FromSql":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildKnownMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "FromSqlScalar":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildKnownMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "FullJoin":
						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsBuilder>.Instance;

						break;

					case "GetCte":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildKnownMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "GetTable":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildTableMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "GroupBy":
						if (global::mooSQL.linq.Linq.Builder.GroupByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.GroupByBuilder>.Instance;

						break;

					case "GroupJoin":
						if (global::mooSQL.linq.Linq.Builder.GroupJoinBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.GroupJoinBuilder>.Instance;

						break;

					case "HasUniqueKey":
						if (global::mooSQL.linq.Linq.Builder.HasUniqueKeyBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.HasUniqueKeyBuilder>.Instance;

						break;

					case "Having":
						if (global::mooSQL.linq.Linq.Builder.WhereBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.WhereBuilder>.Instance;

						break;

					case "IgnoreFilters":
						if (global::mooSQL.linq.Linq.Builder.IgnoreFiltersBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.IgnoreFiltersBuilder>.Instance;

						break;

					case "InlineParameters":
						if (global::mooSQL.linq.Linq.Builder.InlineParametersBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InlineParametersBuilder>.Instance;

						break;

					case "InnerJoin":
						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsBuilder>.Instance;

						break;

					case "Insert":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "InsertAll":
						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "InsertFirst":
						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "InsertOrUpdate":
						if (global::mooSQL.linq.Linq.Builder.InsertOrUpdateBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertOrUpdateBuilder>.Instance;

						break;

					case "InsertWhenNotMatchedAnd":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.InsertWhenNotMatched.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.InsertWhenNotMatched>.Instance;

						break;

					case "InsertWithIdentity":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder>.Instance;

						break;

					case "InsertWithOutput":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder>.Instance;

						break;

					case "InsertWithOutputInto":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder>.Instance;

						break;

					case "Intersect":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "IntersectAll":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "Into":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.Into.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder.Into>.Instance;

						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "IsTemporary":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "Join":
						if (global::mooSQL.linq.Linq.Builder.JoinBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.JoinBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsBuilder.CanBuildJoin(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsBuilder>.Instance;

						break;

					case "LeftJoin":
						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsBuilder>.Instance;

						break;

					case "LoadWith":
						if (global::mooSQL.linq.Linq.Builder.LoadWithBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.LoadWithBuilder>.Instance;

						break;

					case "LoadWithAsTable":
						if (global::mooSQL.linq.Linq.Builder.LoadWithBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.LoadWithBuilder>.Instance;

						break;

					case "LoadWithInternal":
						if (global::mooSQL.linq.Linq.Builder.LoadWithBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.LoadWithBuilder>.Instance;

						break;

					case "LongCount":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "LongCountAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "Max":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "MaxAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "Merge":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.Merge.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.Merge>.Instance;

						break;

					case "MergeInto":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.MergeInto.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.MergeInto>.Instance;

						break;

					case "MergeWithOutput":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder>.Instance;

						break;

					case "MergeWithOutputInto":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder>.Instance;

						break;

					case "Min":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "MinAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "MultiInsert":
						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "OfType":
						if (global::mooSQL.linq.Linq.Builder.OfTypeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OfTypeBuilder>.Instance;

						break;

					case "On":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.On.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.On>.Instance;

						break;

					case "OnTargetKey":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.On.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.On>.Instance;

						break;

					case "OrderBy":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "OrderByDescending":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "QueryName":
						if (global::mooSQL.linq.Linq.Builder.QueryNameBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.QueryNameBuilder>.Instance;

						break;

					case "RemoveOrderBy":
						if (global::mooSQL.linq.Linq.Builder.RemoveOrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.RemoveOrderByBuilder>.Instance;

						break;

					case "RightJoin":
						if (global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsLinqBuilder>.Instance;

						if (global::mooSQL.linq.Linq.Builder.AllJoinsBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AllJoinsBuilder>.Instance;

						break;

					case "SchemaName":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "Select":
						if (global::mooSQL.linq.Linq.Builder.SelectBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SelectBuilder>.Instance;

						break;

					case "SelectDistinct":
						if (global::mooSQL.linq.Linq.Builder.DistinctBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.DistinctBuilder>.Instance;

						break;

					case "SelectMany":
						if (global::mooSQL.linq.Linq.Builder.SelectManyBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SelectManyBuilder>.Instance;

						break;

					case "SelectQuery":
						if (global::mooSQL.linq.Linq.Builder.SelectQueryBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SelectQueryBuilder>.Instance;

						break;

					case "ServerName":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "Set":
						if (global::mooSQL.linq.Linq.Builder.UpdateBuilder.Set.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.UpdateBuilder.Set>.Instance;

						break;

					case "Single":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "SingleAsync":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "SingleOrDefault":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "SingleOrDefaultAsync":
						if (global::mooSQL.linq.Linq.Builder.FirstSingleBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.FirstSingleBuilder>.Instance;

						break;

					case "Skip":
						if (global::mooSQL.linq.Linq.Builder.TakeSkipBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TakeSkipBuilder>.Instance;

						break;

					case "Sum":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "SumAsync":
						if (global::mooSQL.linq.Linq.Builder.AggregationBuilder.CanBuildAsyncMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.AggregationBuilder>.Instance;

						break;

					case "TableFromExpression":
						if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildTableMethods(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;

						break;

					case "TableID":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "TableName":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "TableOptions":
						if (global::mooSQL.linq.Linq.Builder.TableAttributeBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TableAttributeBuilder>.Instance;

						break;

					case "TagQuery":
						if (global::mooSQL.linq.Linq.Builder.TagQueryBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TagQueryBuilder>.Instance;

						break;

					case "Take":
						if (global::mooSQL.linq.Linq.Builder.TakeSkipBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TakeSkipBuilder>.Instance;

						break;

					case "ThenBy":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "ThenByDescending":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "ThenLoad":
						if (global::mooSQL.linq.Linq.Builder.LoadWithBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.LoadWithBuilder>.Instance;

						break;

					case "ThenOrBy":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "ThenOrByDescending":
						if (global::mooSQL.linq.Linq.Builder.OrderByBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.OrderByBuilder>.Instance;

						break;

					case "Truncate":
						if (global::mooSQL.linq.Linq.Builder.TruncateBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.TruncateBuilder>.Instance;

						break;

					case "Union":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "UnionAll":
						if (global::mooSQL.linq.Linq.Builder.SetOperationBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.SetOperationBuilder>.Instance;

						break;

					case "Update":
						if (global::mooSQL.linq.Linq.Builder.UpdateBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.UpdateBuilder>.Instance;

						break;

					case "UpdateWhenMatchedAnd":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenMatched.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenMatched>.Instance;

						break;

					case "UpdateWhenMatchedAndThenDelete":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenMatchedThenDelete.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenMatchedThenDelete>.Instance;

						break;

					case "UpdateWhenNotMatchedBySourceAnd":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenNotMatchedBySource.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.UpdateWhenNotMatchedBySource>.Instance;

						break;

					case "UpdateWithOutput":
						if (global::mooSQL.linq.Linq.Builder.UpdateBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.UpdateBuilder>.Instance;

						break;

					case "UpdateWithOutputInto":
						if (global::mooSQL.linq.Linq.Builder.UpdateBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.UpdateBuilder>.Instance;

						break;

					case "Using":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.Using.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.Using>.Instance;

						break;

					case "UsingTarget":
						if (global::mooSQL.linq.Linq.Builder.MergeBuilder.UsingTarget.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MergeBuilder.UsingTarget>.Instance;

						break;

					case "Value":
						if (global::mooSQL.linq.Linq.Builder.InsertBuilder.Value.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.InsertBuilder.Value>.Instance;

						break;

					case "When":
						if (global::mooSQL.linq.Linq.Builder.MultiInsertBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.MultiInsertBuilder>.Instance;

						break;

					case "Where":
						if (global::mooSQL.linq.Linq.Builder.WhereBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.WhereBuilder>.Instance;

						break;

					case "With":
						if (global::mooSQL.linq.Linq.Builder.WithTableExpressionBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.WithTableExpressionBuilder>.Instance;

						break;

					case "WithTableExpression":
						if (global::mooSQL.linq.Linq.Builder.WithTableExpressionBuilder.CanBuildMethod(call, info, builder))
							return Builder<global::mooSQL.linq.Linq.Builder.WithTableExpressionBuilder>.Instance;

						break;


				}

				if (global::mooSQL.linq.Linq.Builder.MethodChainBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.MethodChainBuilder>.Instance;

				if (global::mooSQL.linq.Linq.Builder.QueryExtensionBuilder.CanBuild(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.QueryExtensionBuilder>.Instance;

				if (global::mooSQL.linq.Linq.Builder.TableBuilder.CanBuildAttributedMethods(expr, info, builder))
					return Builder<global::mooSQL.linq.Linq.Builder.TableBuilder>.Instance;


				break;
			}
		}

		if (global::mooSQL.linq.Linq.Builder.ContextRefBuilder.CanBuild(info, builder))
			return Builder<global::mooSQL.linq.Linq.Builder.ContextRefBuilder>.Instance;


		return null;
	}
}
