using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace mooSQL.Generators
{
    [Generator]
    public sealed class MaterializerSourceGenerator : IIncrementalGenerator
    {
        private const string GenerateMaterializerAttributeName = "mooSQL.data.GenerateMaterializerAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var types = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GenerateMaterializerAttributeName,
                    predicate: static (node, _) => node is TypeDeclarationSyntax,
                    transform: static (ctx, _) => GetTypeInfo(ctx))
                .Where(static info => info is not null);

            context.RegisterSourceOutput(types.Collect(), static (spc, source) => Execute(source, spc));
        }

        private static TypeGenInfo? GetTypeInfo(GeneratorAttributeSyntaxContext context)
        {
            if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
                return null;
            if (typeSymbol.TypeKind != TypeKind.Class && typeSymbol.TypeKind != TypeKind.Struct)
                return null;

            var members = new List<MemberGenInfo>();
            foreach (var member in typeSymbol.GetMembers())
            {
                if (member is IPropertySymbol prop && prop.SetMethod != null && !prop.IsStatic)
                {
                    var columnName = GetColumnName(prop);
                    members.Add(new MemberGenInfo(columnName, prop.Name, prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                }
                else if (member is IFieldSymbol field && !field.IsStatic && !field.IsReadOnly && !field.IsImplicitlyDeclared)
                {
                    var columnName = GetColumnName(field);
                    members.Add(new MemberGenInfo(columnName, field.Name, field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                }
            }

            if (members.Count == 0)
                return null;

            return new TypeGenInfo(
                typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                typeSymbol.Name,
                typeSymbol.ContainingNamespace.ToDisplayString(),
                members);
        }

        private static string GetColumnName(ISymbol member)
        {
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == "mooSQL.data.SooColumnAttribute")
                {
                    if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string name && !string.IsNullOrWhiteSpace(name))
                        return name;
                    foreach (var named in attr.NamedArguments)
                    {
                        if (named.Key == "Name" && named.Value.Value is string n && !string.IsNullOrWhiteSpace(n))
                            return n;
                    }
                }
            }
            return member.Name;
        }

        private static void Execute(ImmutableArray<TypeGenInfo?> types, SourceProductionContext context)
        {
            var valid = types.Where(t => t is not null).Cast<TypeGenInfo>().ToList();
            if (valid.Count == 0) return;

            var registration = new StringBuilder();
            registration.AppendLine("// <auto-generated />");
            registration.AppendLine("using System;");
            registration.AppendLine("using System.Data.Common;");
            registration.AppendLine("using System.Runtime.CompilerServices;");
            registration.AppendLine("using mooSQL.data;");
            registration.AppendLine();
            registration.AppendLine("namespace mooSQL.data.Generated");
            registration.AppendLine("{");
            registration.AppendLine("    internal static class MaterializerRegistration");
            registration.AppendLine("    {");
            registration.AppendLine("        [ModuleInitializer]");
            registration.AppendLine("        internal static void Init()");
            registration.AppendLine("        {");

            foreach (var type in valid)
            {
                var materializerSource = GenerateMaterializer(type);
                context.AddSource($"{type.TypeName}_Materializer.g.cs", SourceText.From(materializerSource, Encoding.UTF8));

                var typeFull = type.TypeFullName;
                var materializerType = string.IsNullOrEmpty(type.Namespace)
                    ? $"{type.TypeName}_Materializer"
                    : $"global::{type.Namespace}.{type.TypeName}_Materializer";
                registration.AppendLine($"            MaterializerRegistry.Register(typeof({typeFull}), (r, d) => {materializerType}.Deserialize(r, d));");
            }

            registration.AppendLine("        }");
            registration.AppendLine("    }");
            registration.AppendLine("}");

            context.AddSource("MaterializerRegistration.g.cs", SourceText.From(registration.ToString(), Encoding.UTF8));
        }

        private static string GenerateMaterializer(TypeGenInfo type)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Data.Common;");
            sb.AppendLine("using mooSQL.data;");
            sb.AppendLine();
            sb.AppendLine($"namespace {type.Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    internal static class {type.TypeName}_Materializer");
            sb.AppendLine("    {");
            sb.AppendLine($"        internal static {type.TypeFullName} Deserialize(DbDataReader reader, DBInstance db)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var result = new {type.TypeFullName}();");
            sb.AppendLine("            for (int i = 0; i < reader.FieldCount; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                switch (reader.GetName(i))");
            sb.AppendLine("                {");

            foreach (var member in type.Members)
            {
                sb.AppendLine($"                    case \"{member.ColumnName}\":");
                sb.AppendLine($"                        result.{member.MemberName} = ({member.TypeName})ColumnValueReader.ReadValue(reader, i, typeof({member.TypeName}), null, db);");
                sb.AppendLine("                        break;");
            }

            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            return result;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private sealed class TypeGenInfo
        {
            public TypeGenInfo(string typeFullName, string typeName, string ns, List<MemberGenInfo> members)
            {
                TypeFullName = typeFullName;
                TypeName = typeName;
                Namespace = ns;
                Members = members;
            }

            public string TypeFullName { get; }
            public string TypeName { get; }
            public string Namespace { get; }
            public List<MemberGenInfo> Members { get; }
        }

        private sealed class MemberGenInfo
        {
            public MemberGenInfo(string columnName, string memberName, string typeName)
            {
                ColumnName = columnName;
                MemberName = memberName;
                TypeName = typeName;
            }

            public string ColumnName { get; }
            public string MemberName { get; }
            public string TypeName { get; }
        }
    }
}
